### ISSUE TITLE
command 'wrapSelection.quote.backtick' not found

### ISSUE THREAD

**Issue by anatoli26** [gko/wrap#15]
When I open vscode, select a text and press `` ` `` (backtick), I get a warning: `command 'wrapSelection.quote.backtick' not found`.

Then I press a single quote `'` and the text becomes wrapped with single quotes. Then I press Ctrl + z to undo that, and with the text still selected press again `` ` `` (backtick) and now it works!

System info:

```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-106-generic
Wrap Selection: v0.8.0
```

**Comment by liangjiancang** [comment]
Same problem, plz fix it.

**Comment by gko** [comment]
fixed. Sorry everyone
