### ISSUE TITLE
Can the extension accept args?

### ISSUE THREAD

**Issue by stephancasas** [gko/wrap#27]
Howdy, and thank you for creating this extension. It's quite useful!

I'm interested in passing the wrap pattern as an arg so that I can define a keyboard shortcut for the specific pattern I wish to use — something along the lines of what I've done with the `sendSequence` command here:

```json
{
    "key": "f12",
    "command": "workbench.action.terminal.sendSequence",
    "args": {
      "text": "\u0003"
    }
}
```

Extending that syntax, perhaps it would look something like:

```json
{
    "key": "$",
    "command": "wrapSelection",
    "args": "\\$\\{${text}\\}"
}
```

If a pattern is already declared in settings.json, perhaps the arg could reference that instead.

Any thoughts? If you're busy, I'd be willing to take a crack at it and open a pull request.

Cheers!

**Comment by quangvinh1225** [comment]
@stephancasas You can register a keyboard shortcut for a pattern in settings.json like below:

```
{
        "key": "ctrl+Alt+L",
        "command": "wrapSelection.pattern",
        "args": "translate"
}
```

**Comment by stephancasas** [comment]
Super. That's exactly what I was wanting. Thanks! 🎉
